---
- name: Deploy Prometheus, Loki, and Promtail
  hosts: backend
  become: true

  vars:
    config_dir: /opt/monitoring
    pushgateway_ip: "{{ hostvars[groups['frontend'][0]]['private_ip_address'] }}"
    loki_url: "http://{{ ansible_default_ipv4.address }}:3100"

  tasks:
    - name: Create config directories
      file:
        path: "{{ config_dir }}/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - prometheus
        - promtail

    - name: Template Prometheus config
      template:
        src: ../templates/prometheus.yml.j2
        dest: "{{ config_dir }}/prometheus/prometheus.yml"
        mode: '0644'

    - name: Template Promtail config
      template:
        src: ../templates/promtail-config.yml.j2
        dest: "{{ config_dir }}/promtail/promtail-config.yml"
        mode: '0644'

    - name: Run Prometheus
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus:v2.53.5
        state: started
        restart_policy: always
        ports:
          - "9090:9090"
        volumes:
          - "{{ config_dir }}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro,z"
          - "prometheus_data:/prometheus"
        command:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--enable-feature=native-histograms"
          - "--web.enable-remote-write-receiver"

    - name: Run Loki
      community.docker.docker_container:
        name: loki
        image: grafana/loki:2.9.0
        state: started
        restart_policy: always
        ports:
          - "3100:3100"
        volumes:
          - "loki_data:/loki"

    - name: Run Promtail
      community.docker.docker_container:
        name: promtail
        image: grafana/promtail:3.2.1
        state: started
        restart_policy: always
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro,z"
          - "{{ config_dir }}/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro,z"
        command:
          - "-config.file=/etc/promtail/promtail-config.yml"
