---
- name: Synchronize seed libraries
  ansible.builtin.import_playbook: sync_seed_libraries.yml

- name: Synchronize user libraries
  ansible.builtin.import_playbook: sync_user_libraries.yml

- name: Create users
  ansible.builtin.import_playbook: create_users.yml
